STATUS_QUEUED = "QUEUED"
STATUS_ASSIGNED = "ASSIGNED"
STATUS_DOWNLOADING = "DOWNLOADING"
STATUS_RENDERING = "RENDERING"
STATUS_PRINTING = "PRINTING"
STATUS_SUCCESS = "SUCCESS"
STATUS_FAILED = "FAILED"

ACTIVE_STATES = {
    STATUS_QUEUED,
    STATUS_ASSIGNED,
    STATUS_DOWNLOADING,
    STATUS_RENDERING,
    STATUS_PRINTING,
}

TERMINAL_STATES = {STATUS_SUCCESS, STATUS_FAILED}

VALID_STATUS_TRANSITIONS = {
    STATUS_QUEUED: {STATUS_ASSIGNED, STATUS_FAILED},
    STATUS_ASSIGNED: {STATUS_DOWNLOADING, STATUS_FAILED},
    STATUS_DOWNLOADING: {STATUS_RENDERING, STATUS_FAILED},
    STATUS_RENDERING: {STATUS_PRINTING, STATUS_FAILED},
    STATUS_PRINTING: {STATUS_SUCCESS, STATUS_FAILED},
    STATUS_SUCCESS: set(),
    STATUS_FAILED: set(),
}

